development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  twilio_account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  twilio_account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
